#include<stdio.h>
#include<stdlib.h>

#include<omp.h>
#include<mpi.h>


#include"read_write.h"

/*
    write_pgm(): print the playground (a char array with size k*k)
        into the requested file
    @param: 
    fname:  file name where write the 'world' matrix
    k:      The size of the square-matrix the playground
    world:  matrix of characher that needs to be written 
*/

void write_pgm_serial(char* fname, int k, char* world)
{
    FILE* file; 
    file = fopen(fname, "w"); 
    // header: to conform to requirements: 
    fprintf(file, "P5\n# generated by\n# Isac Pasianotto \n%d %d\n%d\n", k, k, 1);
    fwrite(world, sizeof(char), k*k, file);  
    fclose(file); 
    return;
}


/*
    write_pgm(): print the playground (a char array with size k*k)
        into the requested file
    @param: 
    fname:      file name where write the 'world' matrix
    std_size:   the size of the array all but the last process is working on    
    k:          The size of the array each process is working on (== std_size if rank != size-1)
    world:      vector of characher eahc process must write 
    rank:       the rank of the process that is executing the function
    size:       the total number of mpi-processes involved 
*/

void write_pgm_parallel(char *fname, int std_size, int k, char* world, int rank, int size)
{
    
    /*
    
        Note:    WORK IN PROGRESS....
        
                I've tried to parallelize this function, but I've not been able to do it.
                Due to the fact that I have to submit the assignment due to a certain deadline,
                I've decided to submit the code as it is, and I'll try to fix it later.

                I've tested both an MPI-IO approach and try to implement a parallel version of the 
                writing_pgm_serial() function, but I've not yet been able to do it.

                For now This code just call the write_pgm_serial().
    */
    
    /*
    int offset, start;

    FILE* file; 
    start = rank*std_size;

    file = fopen(fname, "w");
    // header: to conform to requirements:
    fprintf(file, "P5\n# generated by\n#Isac Pasianotto \n%d %d\n%d\n", std_size*size, std_size*std_size, 1);  
    // write the world matrix
    for (int i = 0; i < k; i++){
        offset = (start+46+rank)*sizeof(char); // 46 = header size
        start++; 
        printf("Im'm process %d and at iteration %d I'm writing at offset %d\n", rank, i, offset);
        rewind(file); //need to rewind the file pointer to the beginning of the file
        fseek(file, offset, SEEK_SET);
        fputc(world[i], file);
    }
    fclose(file);
    */
    
    write_pgm_serial(fname, k, world);
    return;
}

